In [ ]:
import torch 

o1 = torch.Tensor([[1,2,3], [1,2,3]]) # batch_size * embed_dim
o2 = torch.Tensor([[4,5,6], [4,5,6]]) # batch_size * embed_dim
o2 = torch.Tensor([[4,5,6], [4,5,6]]) # batch_size * embed_dim
tensor_layer = torch.Tensor([[[1,2,3], 
                              [4,5,6],
                             [7,8,9]], 
                             
                             [[1,2,3], 
                              [4,5,6],
                             [7,8,9]],
                             
                             [[1,2,3], 
                              [4,5,6],
                             [7,8,9]]])

# we flatten each matrix
tensor_product = o1.mm(tensor_layer.view(3, -1)) # view changes shape, mm is matmul
# # |tensor_product| = (batch_size, unknown_dim * tensor_dim)
# tensor_product = tensor_product.view(batch_size, -1, unknown_dim).bmm(o2.unsqueeze(1).permute(0,2,1).contiguous()).squeeze()
# tensor_product = tensor_product.contiguous()

In [ ]:
import numpy as np
import math

def sigmoid(x):
    return 1 / (1 + math.exp(-x))

v = np.array([0.1,0.2,0.3])
w = np.array([0.4,0.5,0.6])
e = np.matmul(np.transpose(v), w) # this gives a scalar !
sigmoid(e)

In [ ]:
tensor_product.shape

In [ ]:
vs = torch.einsum('ijk,ck,cj->ci', tensor_layer, o1, o2)

# svo = torch.concat([vs,vo], 1) 
# final = torch.matmul(svo, W, name='final')

In [ ]:
vs

In [ ]:
o1

In [ ]:
tensor_layer.view(3, -1)

In [1]:
import numpy as np

x = np.array([1, 2])
y = np.array([5, 6])

X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])

Z = np.matmul(X, np.transpose(Y)) # because we want rows with rows, columns with columns 

a = np.matmul(x, X)
b = np.matmul(y, Y)

In [2]:
a

array([ 7, 10])

In [3]:
self_attention = np.dot(a, np.transpose(b)) # both row vectors
self_attention

1249

In [4]:
Z_tensor = np.array([Z])
Z_tensor

array([[[17, 23],
        [39, 53]]])

In [9]:
Z_tensor.shape

(1, 2, 2)

In [5]:
bilinear_prod1 = np.einsum('ijk,j, k', Z_tensor, x, y) # we get a scalar for each slice

In [6]:
bilinear_prod2 = np.einsum('jk,j, k', Z, x, y) # we get just one scalar 

In [7]:
bilinear_prod1

array([1249])

In [10]:
bilinear_prod2

1249