In [1]:
import numpy as np

x = np.array([1, 2])
y = np.array([5, 6])

X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])

Z = np.matmul(X, np.transpose(Y)) # because we want rows with rows, columns with columns 

a = np.matmul(x, X)
b = np.matmul(y, Y)

In [2]:
a

array([ 7, 10])

In [3]:
self_attention = np.dot(a, np.transpose(b)) # both row vectors
self_attention

1249

In [4]:
Z_tensor = np.array([Z])
Z_tensor

array([[[17, 23],
        [39, 53]]])

In [9]:
Z_tensor.shape

(1, 2, 2)

In [5]:
bilinear_prod1 = np.einsum('ijk,j, k', Z_tensor, x, y) # we get a scalar for each slice

In [6]:
bilinear_prod2 = np.einsum('jk,j, k', Z, x, y) # we get just one scalar 

In [7]:
bilinear_prod1

array([1249])

In [10]:
bilinear_prod2

1249